# Generated by Django 2.2.5 on 2019-09-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register_dr_data',
        ),
    ]
