# Generated by Django 2.2.5 on 2019-10-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20190930_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
