# Generated by Django 2.2.5 on 2019-10-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_doctor_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='birthdate',
        ),
    ]
