# Generated by Django 2.2.5 on 2019-10-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_auto_20191004_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='medicalshop_id',
        ),
        migrations.DeleteModel(
            name='Medicalshop',
        ),
        migrations.DeleteModel(
            name='Medicines',
        ),
    ]
