# Generated by Django 2.2.5 on 2019-10-04 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_auto_20191004_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Medicalshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalshop_name', models.CharField(max_length=100)),
                ('medicalshop_address', models.CharField(max_length=100)),
                ('medicalshop_phoneno', models.CharField(max_length=100)),
                ('medicalshop_cert', models.FileField(default='patient_icon.png', upload_to='my_app/img/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines_pic', models.FileField(default='patient_icon.png', upload_to='my_app/img/')),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_description', models.CharField(max_length=100)),
                ('medicine_price', models.CharField(max_length=100)),
                ('medicalshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tbl_Medicalshop')),
            ],
        ),
    ]
