# Generated by Django 2.2.5 on 2019-11-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_auto_20191106_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(default='images/mehul.png', upload_to='my_app/img/'),
        ),
    ]
