# Generated by Django 2.2.5 on 2019-11-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointment',
        ),
    ]
