# Generated by Django 2.2.5 on 2019-11-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('availability_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_app.availability')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Patient')),
            ],
        ),
    ]
