# Generated by Django 2.2.5 on 2019-12-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_app', '0024_auto_20191219_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Medicalshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalshop_name', models.CharField(max_length=100)),
                ('medicalshop_address', models.CharField(max_length=100)),
                ('medicalshop_phoneno', models.CharField(max_length=100)),
                ('medicalshop_cert', models.FileField(default='patient_icon.png', upload_to='my_app/img/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=459)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verfied', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines_pic', models.FileField(default='patient_icon.png', upload_to='my_app/img/')),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_description', models.CharField(max_length=100)),
                ('medicine_price', models.CharField(max_length=100)),
                ('medicalshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tbl_Medicalshop')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('birthdate', models.DateField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('blood_presure', models.CharField(blank=True, max_length=10)),
                ('sugar', models.CharField(blank=True, max_length=10)),
                ('Haemoglobin', models.CharField(blank=True, max_length=10)),
                ('profile_pic', models.FileField(default='images/mehul.png', upload_to='my_app/img/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('clinic', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('about_doc', models.CharField(blank=True, max_length=100)),
                ('profile_pic', models.FileField(default='images/member1.png', upload_to='my_app/img/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail_date', models.DateField()),
                ('start_time', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('availability_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_app.availability')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Patient')),
            ],
        ),
    ]
