# Generated by Django 2.2.5 on 2019-12-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_appointment_availability_doctor_patient_tbl_medicalshop_tbl_medicine_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_medicine',
            name='medicalshop_id',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='availability',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='tbl_Medicalshop',
        ),
        migrations.DeleteModel(
            name='tbl_Medicine',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
