# Generated by Django 2.2.5 on 2020-02-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_appointment_availability_doctor_patient_tbl_medicalshop_tbl_medicine_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=40)),
                ('receiver_email', models.EmailField(max_length=40)),
                ('s_message', models.CharField(blank=True, max_length=500)),
                ('r_message', models.CharField(blank=True, max_length=500)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User')),
            ],
        ),
    ]
