# Generated by Django 2.2.5 on 2020-02-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_remove_chat_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Medicine',
        ),
    ]
