# Generated by Django 2.2.5 on 2020-02-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_delete_tbl_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines_pic', models.FileField(default='patient_icon.png', upload_to='my_app/img/')),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_description', models.CharField(max_length=100)),
                ('medicine_usage', models.CharField(max_length=100)),
                ('medicine_benefits', models.CharField(max_length=100)),
                ('medicine_sideeffects', models.CharField(max_length=100)),
                ('medicine_doc', models.CharField(max_length=100)),
                ('medicalshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tbl_Medicalshop')),
            ],
        ),
    ]
