# Generated by Django 2.2.5 on 2020-02-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_tbl_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Medicine',
        ),
    ]
