# Generated by Django 2.2.5 on 2020-02-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0035_tbl_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_medicine',
            name='medicine_type',
            field=models.CharField(default='hhhhh', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(default='mehul.jpg', upload_to='my_app/img/'),
        ),
    ]
